### ISSUE TITLE
RFSniffer use over 40% of cpu

### ISSUE THREAD

**Issue by ghostmaster75** [jmc265/rpi-433-v3#4]
Hi, 
on my Raspberry PI 3 model B i use in my node-red projenct  the node-red-contrib-rpi-433 palette.
I noticed that the RF Sniffer program uses over 40% of the cpu (often it is 45%). I tried to increase the delay bounce from the node but without getting acceptable results. I think an end-of-cycle sleep time of 100ms is very little in your program.
![immagine](https://user-images.githubusercontent.com/3819353/158056210-17569a3d-d32c-4023-a8e6-8b81af3fcd12.png)
![immagine](https://user-images.githubusercontent.com/3819353/158056283-a04aefb3-e493-4e1c-a601-97cf76bc40be.png)

**Comment by jmc265** [comment]
Hi ghostmaster75

I too got a high CPU usage on my PI when I was using this, I believe it is caused by the endless polling of the pins, but I have never had time to investigate (as I mention in the readme, this code is not mine, it is simply copied from a previously deleted repo).
If you have time to investigate and create a PR for this repo, I would review and merge, but I no longer have a need for this library so cannot provide any further support.
